baseURL: https://stalwart-semifreddo-41b5da.netlify.app
languageCode: zh-cn
title: 千丁百火
theme: hugo-PaperMod

params:
  homeInfoParams:
    Title: Welcome to My Personal Website
    Content: 经验和想象
  socialIcons:
    - name: twitter
      url: https://twitter.com/RODE07081933
    - name: instagram
      url: https://www.instagram.com/ryoshiiyuuz/
    - name: rss
      url: https://stalwart-semifreddo-41b5da.netlify.app/index.xml
    - name: email
      url: rongzhouzheng7@gmail.com

  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true
  
  ShowPostNavLinks: true


menu:
  main:
    - identifier: archive
      name: 文章列表
      url: /archives/
      weight: 10
    - identifier: categories
      name: 话题
      url: /categories/
      weight: 20
    - identifier: search
      name: 搜索
      url: /search/
      weight: 30  
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true



enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true

hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45 # 谷歌统计
# Copyright: Sulv

paginate: 15

