baseURL: https://stalwart-semifreddo-41b5da.netlify.app
languageCode: zh-cn
title: 疑难杂志MazIne
theme: hugo-PaperMod
paginate: 8
#googleAnalytics: UA-123-45 # 谷歌统计
ignoreFiles:
  - obsidian template
  - .obsidian

minify:
  disableXML: true
  minifyOutput: true

permalinks: # 访问博客时网址的显示形式
  post: "/:title/"

params:
  env: production
  defaultTheme: auto
  mainSections: ["posts"]
  homeInfoParams:
    Title: Welcome. 
    Content: >
    疑难杂志 MazIne, 是由 [Ryuuzzor](https://stalwart-semifreddo-41b5da.netlify.app/about/) 发起的媒体计划，也是一次初步的尝试。
    
    >
    这里主要探讨个人的切身的困扰、悬而未决的问题，认真分享一些 Lifehacks 生活小妙招，以及个人认为值得被了解的人、事、物。除此之外，还可能尝试写一些新鲜的、但暂时没想好的内容。
    
    >
    为了避免陷入某种信息同温层（[filter bubble](https://en.wikipedia.org/wiki/Filter_bubble)），偶尔会邀请一些朋友——如果没有稿费他们也愿意的话——来做一些分享。
    
    >
    目前，较长的文章会在首页呈现，为了美观，大多数情况都会配一张题图作为封面。相较之下，更为随意、零碎的想法和观点会在 [Daily Nuts](https://stalwart-semifreddo-41b5da.netlify.app/essays/)（点击顶部「坚果」入口）中抒发。
  socialIcons:
    - name: instagram
      url: https://www.instagram.com/ryuuzzor/
    - name: rss
      url: https://stalwart-semifreddo-41b5da.netlify.app/index.xml
    - name: email
      url: rongzhouzheng7@gmail.com

  cover:
    linkFullImages: true
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page


  fuseOpts:       #搜索页的相关配置
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowFullTextinRSS: true
  ShowRssButtonInSectionTermList: ture
  ShowToc: true
  TocOpen: true
  disableAnchoredHeadings: ture

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  assets:
    favicon: "img/Z.png"
    favicon16x16: "img/Z.png"
    favicon32x32: "img/Z.png"
    apple_touch_icon: "img/Z.png"
    safari_pinned_tab: "img/Z.png"

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: archive
      name: 文章列表
      url: /archives/
      weight: 10
    - identifier: essays
      name: 坚果
      url: /essays/
      weight: 20
    - identifier: tags
      name: 话题
      url: /tags/
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true

enableInlineShortcodes: true
enableEmoji: true # 允许使用 Emoji 表情，建议 true
enableRobotsTXT: true # 允许爬虫抓取到搜索引擎，建议 true
hasCJKLanguage: true # 自动检测是否包含 中文日文韩文 如果文章中使用了很多中文引号的话可以开启

buildDrafts: false
buildFuture: false
buildExpired: false

outputs:
  home:
    - HTML
    - RSS
    - JSON
